In [1]:
pwd

u'E:\\GitHub\\ipython.notebook.dir'

In [2]:
%pylab
import sys
sys.path.append(r'D:\opencv249\sources\modules\python\test')

import os
import cv2
import transformations as tf
'一些短别名:'
tf.e2m = tf.euler_matrix
tf.m2e = tf.euler_from_matrix
tf.q2m = tf.quaternion_matrix
tf.m2q = tf.quaternion_from_matrix
tf.e2q = tf.quaternion_from_euler
tf.q2e = tf.euler_from_quaternion
tf.m2r = tf.rotation_from_matrix
tf.r2m = tf.rotation_matrix

'angle <--> radian:'
a2r = np.pi / 180
r2a = 180 / np.pi

Using matplotlib backend: Qt4Agg
Populating the interactive namespace from numpy and matplotlib


In [38]:
'测试： 左乘表示固定轴旋转，√'
axes='sxyz'
x,y,z=10,20,34
ms=tf.e2m(x,y,z, axes)
print ms

axes='rxyz'
mr=tf.e2m(x,y,z, axes)
print mr

'单轴旋转 r/s 应该是同样结果'
axes='rxyz'
mx=tf.e2m(x, 0, 0, axes) 
my=tf.e2m(0, y, 0, axes)
mz=tf.e2m(0, 0, z, axes)
print '---------------'
# print mx
# print my
# print mz
mleft=mz.dot(my).dot(mx)
mright=mx.dot(my).dot(mz)
'助记：rot-frame 对应 right-multiply'
assert np.allclose(ms, mleft)
assert np.allclose(mr, mright)

[[-0.34628631  0.8653904   0.36219505  0.        ]
 [ 0.21590915  0.44923616 -0.86693143  0.        ]
 [-0.91294525 -0.22200526 -0.34241004  0.        ]
 [ 0.          0.          0.          1.        ]]
[[-0.34628631 -0.21590915  0.91294525  0.        ]
 [-0.02248604  0.97478615  0.22200526  0.        ]
 [-0.93785936  0.05634886 -0.34241004  0.        ]
 [ 0.          0.          0.          1.        ]]
---------------
[[ True False False  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


(0.86539039505529258, 0.86539039505529269, False)

In [25]:
np.all?

In [21]:
tf.e2m?

In [3]:
'测试 pcl_kinfu_app 使用 -r 参数与不用时的差异'
pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-slope-7x10-264-r-2.csv'
pose_mat = loadtxt(pose_file, delimiter=',')
tvecsDepth = pose_mat[:, :3]
lns = plot(tvecsDepth)
# legend(lns, list('xyz'))

pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-slope-7x10-285.csv'
pose_mat = loadtxt(pose_file, delimiter=',')
tvecsDepth = pose_mat[:, :3]
lns2 = plot(tvecsDepth)
legend(lns+lns2, list('xyzabc'))

# pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-slope-7x10-T0=0.csv'
# pose_mat = loadtxt(pose_file, delimiter=',')
# tvecsDepth = pose_mat[:, :3]+(1.5, 1.5, -0.3)
# plot(tvecsDepth)


In [6]:
# generated by pcl_kinfu_app & OpencvCalib:
'3x4, t2b-refine'
'---------------1'
pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-smt-d100-sz35.8-r2l-t2b-refine.csv'
extrinsics_xml = r'E:\GitHub\OpenniCeshi\data\openNI132_data_registration_4x3\smt-d100-sz35.8-r2l-t2b-refine_calib\extrinsics.xml'

'horizon-move-part1, c-r(center->right)'
pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-smt-d100-sz35.8-horizon-move-part1.csv'
'---------------2'
extrinsics_xml = r'E:\GitHub\OpenniCeshi\data\openNI132_data_registration_4x3\smt-d100-sz35.8-horizon-move-part1_calib\extrinsics-3x4.xml'

'---------------3'
extrinsics_xml = r'E:\GitHub\OpenniCeshi\data\openNI132_data_registration_4x3\smt-d100-sz35.8-horizon-move-part1_calib\extrinsics-4x3.xml'

'vertical, c-t-b-c'
'---------------4'
pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-smt-d100-sz35.8-vertical-move.csv'
extrinsics_xml = r'E:\GitHub\OpenniCeshi\data\openNI132_data_registration_4x3\smt-d100-sz35.8-vertical-move_calib\extrinsics-4x3.xml'

'zrot-7x8, 先逆时针'
'---------------5'
pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-smt-d100-zrot-7x8.csv'
extrinsics_xml = r'E:\GitHub\OpenniCeshi\data\openNI132_data_registration_7x8\smt-d100-zrot-7x8_calib\extrinsics.xml'

'xyzrot-7x8-3axes, xyz先后转动'
pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-smt-d100-xyzrot-7x8-3axes.csv'
'608 frmaes:'
extrinsics_xml = r'E:\GitHub\OpenniCeshi\data\openNI132_data_registration_7x8\smt-d100-xyzrot-7x8-3axes_calib\extrinsics0.xml'
'1034 frames:'
extrinsics_xml = r'E:\GitHub\OpenniCeshi\data\openNI132_data_registration_7x8\smt-d100-xyzrot-7x8-3axes_calib\extrinsics1.xml'
'---------------6'
extrinsics_xml = r'E:\GitHub\OpenniCeshi\data\openNI132_data_registration_7x8\smt-d100-xyzrot-7x8-3axes_calib\extrinsics1-22.3.xml'

'xyztrans, 7x8, 测试平移'
pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-smt-d100-xyztrans-7x8-refine.csv'
'---------------7'
extrinsics_xml = r'E:\GitHub\OpenniCeshi\data\openNI132_data_registration_7x8\smt-d100-xyztrans-7x8-refine_calib\extrinsics.xml'

'bigboard-d130-7x10.oni, 大板三轴乱动'
pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-d130-7x10.csv'
'---------------8'
extrinsics_xml = r'E:\GitHub\OpenniCeshi\data\openNI1.3_data_registration_7x9\bigboard-d130-7x10_calib\extrinsics.xml'

'bigboard-slope-7x10, 大板子斜着转'
'---------------9'
pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-slope-7x10-264.csv'
# pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-slope-7x10-285-T0=0.csv'
pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-slope-7x10-285.csv'
# extrinsics_xml = r'E:\GitHub\OpenniCeshi\data\bigboard-slope-7x10_calib\extrinsics-22.3.xml'
extrinsics_xml = r'E:\GitHub\OpenniCeshi\data\openni132_registration_7x10\bigboard-slope-7x10_calib\extrinsics-50.xml'

'smallboard, horizon, c-r-l-c, 7x8'
# pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-smallboard-d100-7x8.csv'
# extrinsics_xml = r'E:\GitHub\OpenniCeshi\data\smallboard-d100-7x8_calib\extrinsics-8x7.xml'

'horizon-move, c-r-l-c'
# pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-smt-d100-sz35.8-horizon-move.csv'
# extrinsics_xml = r"E:\GitHub\OpenniCeshi\data\openNI132_data_registration_4x3\smt-d100-sz35.8-horizon-move_calib\extrinsics-3x4.xml"
# extrinsics_xml = r"E:\GitHub\OpenniCeshi\data\openNI132_data_registration_4x3\smt-d100-sz35.8-horizon-move_calib\extrinsics-4x3.xml"

'smt-d100-7x8-move-pause, A4小纸'
# pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-smt-d100-7x8-move-pause.csv'
# extrinsics_xml = r'E:\GitHub\OpenniCeshi\data\openNI132_data_registration_7x8\smt-d100-7x8-move-pause_calib\extrinsics-1456.xml'

'bigboard-7x10-move-pause'
pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-7x10-move-pause.csv'
extrinsics_xml = r'E:\GitHub\OpenniCeshi\data\openni132_registration_7x10\bigboard-7x10-move-pause_calib\extrinsics-1846.xml'

'bigboard-7x10-move-pause-f100~f990.oni'
# pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-shit90.csv'
# extrinsics_xml = r'E:\oni_data\openni132_registration_7x10\shit90_calib\extrinsics.xml'
pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-7x10-move-pause-f100~f990.csv' #total: 89
pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-7x10-move-pause-f100~f990-raw_frames.csv' #total: 91
pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-7x10-move-pause-f100~f990-raw_frames-90-urf.csv' #total: 90
# pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-7x10-move-pause-f100~f990-89-cv_extr.csv'
'-urf, -cv_extr, 90, 此文件确实与 extrinsics.xml 曲线重合； rmse == 0'
pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-7x10-move-pause-f100~f990-urf-90-cv_extr.csv'
'-cv_extr_hint, 用 extrinsics.xml 做初值, 帧数太少，看不出什么； 曲线与 -urf-90 几乎完全重合（数值看起来不同）'
pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-7x10-move-pause-f100~f990-urf-90-cv_extr_hint.csv'
'之前一直带着 -r -ic, 这里去掉它们'
# pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-7x10-move-pause-f100~f990-urf-90-no-r-ic.csv'
extrinsics_xml = r'E:\oni_data\openni132_registration_7x10\bigboard-7x10-move-pause-f100~f990_calib\extrinsics.xml'


'2014/12/18, 之前 oni 文件在 pcl 处理有掉帧，不确定是不是 niviewer 的问题'
# pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-move_around-2.csv'
# extrinsics_xml = r'E:\oni_data\openni132_registration_7x10\bigboard-move_around-2_calib\extrinsics.xml'

# pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-slow-refine.csv'
# pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-slow-refine-2061-urf.csv'
# pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-slow-refine-2056-no-urf.csv'
# # pose_file = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-slow-refine-raw_frames-2.csv'
# extrinsics_xml = r'E:\oni_data\openni132_registration_7x10\bigboard-slow-refine_calib\extrinsics.xml'


'2014/12/18, \xe4\xb9\x8b\xe5\x89\x8d oni \xe6\x96\x87\xe4\xbb\xb6\xe5\x9c\xa8 pcl \xe5\xa4\x84\xe7\x90\x86\xe6\x9c\x89\xe6\x8e\x89\xe5\xb8\xa7\xef\xbc\x8c\xe4\xb8\x8d\xe7\xa1\xae\xe5\xae\x9a\xe6\x98\xaf\xe4\xb8\x8d\xe6\x98\xaf niviewer \xe7\x9a\x84\xe9\x97\xae\xe9\xa2\x98'

In [7]:
print os.path.isfile(extrinsics_xml)
print os.path.isfile(pose_file)

True
True


In [9]:
'以下说明， cv_extr 做初值没有任何提升'
from lxml import etree
psr = etree.XMLParser(remove_blank_text=True)

def plotRvecs(fname):
    if fname.endswith('.csv'):
        pose_mat = loadtxt(fname, delimiter=',')
        rvecsDepth = pose_mat[:, 3:]
        plot(rvecsDepth)
#     elif fname.endswith('.xml'):
#         tree = etree.parse(fname, parser=psr)
#         rt = tree.getroot()
#         tvecsColor = []
#         for i, iframe in enumerate(rt):
#             tvecsColor.append([float(num) for num in iframe.xpath('t/data')[0].text.split()])
#         tvecsColor = np.asarray(tvecsColor)
    pass

def plotTvecs(fname):
    if fname.endswith('.csv'):
        pose_mat = loadtxt(fname, delimiter=',')
        tvecsDepth = pose_mat[:, :3]
        plot(tvecsDepth)
#     elif fname.endswith('.xml'):
#         tree = etree.parse(fname, parser=psr)
#         rt = tree.getroot()
#         tvecsColor = []
#         for i, iframe in enumerate(rt):
#             tvecsColor.append([float(num) for num in iframe.xpath('t/data')[0].text.split()])
#         tvecsColor = np.asarray(tvecsColor)/1000
#         plot(tvecsColor)
    pass

def diffCsvs(fn1, fn2):
    extStr = '.csv'
    assert fn1.endswith(extStr) and fn2.endswith(extStr)
    '2 pose_mats:'
    m1 = loadtxt(fn1, delimiter=',')
    m2 = loadtxt(fn2, delimiter=',')
    return np.abs(m1-m2).mean(axis=0)
    
# fn = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-7x10-move-pause-f100~f990-urf-90-cv_extr.csv'
# plotTvecs(fn)
# fn = r'E:\oni_data\openni132_registration_7x10\bigboard-7x10-move-pause-f100~f990_calib\extrinsics.xml'

'以下说明， cv_extr 做初值没有任何提升'
'-no-r-ic'
# fn = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-7x10-move-pause-f100~f990-urf-90-no-r-ic.csv'
# plotRvecs(fn)
# fn = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-7x10-move-pause-f100~f990-urf-90-cv_extr_hint-no-r-ic.csv'
# plotRvecs(fn)

'-r-ic'
fn = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-7x10-move-pause-f100~f990-urf-90.csv'
plotRvecs(fn)
fn_hint = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-7x10-move-pause-f100~f990-urf-90-cv_extr_hint.csv'
plotRvecs(fn_hint)
print 'diffCsvs(fn, fn_hint)', diffCsvs(fn, fn_hint)

'视频 2061 帧'
fn = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-slow-refine-2061-urf.csv'
plotRvecs(fn)
fn_hint = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-slow-refine-2061-urf-cv_extr_hint.csv'
plotRvecs(fn_hint)
print 'diffCsvs(fn, fn_hint)', diffCsvs(fn, fn_hint)

# fn = r'E:\ABOUT C++\libs\pcl-master-6d0343d1b7\_build\gpu\kinfu\tools\pose_file-bigboard-7x10-move-pause-f100~f990-urf-90-cv_extr_hint.csv'
# plotTvecs(fn)


diffCsvs(fn, fn_hint) [  1.20000000e-05   6.33333333e-06   2.71111111e-06   5.22222222e-07
   2.36847778e-06   2.71794444e-06   3.38977778e-06]
diffCsvs(fn, fn_hint) [  2.81168365e-04   7.11014071e-05   2.42955519e-04   3.41644833e-05
   6.27367607e-05   1.47324941e-04   2.21503825e-05]


In [55]:
'---------------处理 pcl_kinfu_app 生成的 csv'
pose_mat = loadtxt(pose_file, delimiter=',')
tvecsDepth = pose_mat[:, :3]
rvecsDepth = pose_mat[:, 3:]
eulerDepth = np.asarray([tf.q2e([q[1], q[2], q[3], q[0]], axes='rxyz') for q in rvecsDepth])
matDepth = np.asarray([tf.q2m([q[1], q[2], q[3], q[0]]) for q in rvecsDepth])
print rvecsDepth.shape
# print rvecsDepth

'接上个 cell'
print eulerDepth.shape
# print eulerDepth

'接上个 cell'
# xs = range(eulerDepth.size)

# figure('111')
# plot(eulerDepth[:, 0], 'r')
# plot(eulerDepth[:, 1], 'g')
# plot(eulerDepth[:, 2], 'b')

# figure('222')
fig = figure('1-eulerDepth-bgr')
plot(eulerDepth, ) #与 111 相反， b,g,r 顺序
savefig(fig.canvas.get_window_title())


'---------------处理 OpencvCalib 生成的 extrinsics.xml'
from lxml import etree
psr = etree.XMLParser(remove_blank_text=True)
tree = etree.parse(extrinsics_xml, parser=psr)
rt = tree.getroot()

# Rodrigues 向量：
rvecsColor = []
tvecsColor = []
# for iframe in rt:
for i, iframe in enumerate(rt):
    rvecsColor.append([float(num) for num in iframe.xpath('r/data')[0].text.split()])
#     rvecsColor.append(map(float, iframe.xpath('r/data')[0].text.split())) # python 2, 3 不兼容， 所以不用
    tvecsColor.append([float(num) for num in iframe.xpath('t/data')[0].text.split()])
    pass

rvecsColor = np.asarray(rvecsColor)
tvecsColor = np.asarray(tvecsColor)
# rvecsColor

# dst, _ = cv2.Rodrigues(rvecsColor[0])
# eulerColor = np.asarray([tf.euler_from_matrix(cv2.Rodrigues(rod)[0]) for rod in rvecsColor]) #good √
# R0 = cv2.Rodrigues(rvecsColor[0])[0].T
'---------------'
eulerColor = []
eulerColor2 = [] # 'R0.T *' 处理过的
'camera -> world 坐标系变换：'
matColor = np.asarray([cv2.Rodrigues(rod)[0].T for rod in rvecsColor]) #---------------有没有 .T ? 应该有
matColor2 = []
R0 = matColor[0]
# for rod in rvecsColor:
#     Ri = cv2.Rodrigues(rod)[0].T
for Ri in matColor:
    eulerColor.append(tf.m2e(Ri, axes='rxyz'))
    '--2:'
#     newRi = np.dot(R0.T, R0.T).dot(Ri).dot(R0) #貌似错了
    
    '--1:'
#     newRi = np.dot(R0.T, Ri).dot(R0.T).dot(R0) #---------------仅仅 R0.T * Ri， （全 .T 之后， 见上 line58)
    newRi = np.dot(R0.T, Ri) #---------------??
#     newRi = np.dot(Ri, R0.T) #---------------×
    eulerColor2.append(tf.m2e(newRi, axes='rxyz')) #R0.T * (R0.T * Ri) * R0
#     eulerColor2.append(tf.euler_from_matrix(np.dot(Ri, R0.T), axes='rxyz')) #尝试右乘 ×
    matColor2.append(newRi)
    pass

matColor2 = np.asarray(matColor2)
matDiff = np.asarray([np.dot(matDepth[i][:3, :3].T, matColor2[i]) for i in range(min(matDepth.shape[0], matColor2.shape[0]))])

eulerColor = np.asarray(eulerColor)
eulerColor2 = np.asarray(eulerColor2)

'---------------一些比较测试'
#333
fig = figure('2-eulerColor-orig')
plot(eulerColor)
savefig(fig.canvas.get_window_title())

#444
fig = figure('3-eulerColor-newRi')
plot(eulerColor2)
savefig(fig.canvas.get_window_title())

fig = figure('4-euler-depth-color')
plot(eulerDepth)
plot(eulerColor2)
savefig(fig.canvas.get_window_title())

fig = figure('5-matDiff-main-diagonal')
plot(matDiff[:,0,0])
plot(matDiff[:,1,1])
plot(matDiff[:,2,2])
savefig(fig.canvas.get_window_title())

fig = figure('6-matDiff-9-elems')
plot(matDiff.reshape((matDiff.shape[0], 9)))
savefig(fig.canvas.get_window_title())

'matDiff 转成轴角表示'
m = matDiff[0]
fig = figure('7-matDiff-rodrigues-angle')
plot([np.linalg.norm(cv2.Rodrigues(m)[0]) for m in matDiff])
savefig(fig.canvas.get_window_title())

# 'm-e, 求行列式, 应该结果接近 0 @孙国飞。已否定'
# fig = figure('matDiff-eye-det')
# plot([np.linalg.det(m-np.eye(3)) for m in matDiff ])
# savefig(fig.canvas.get_window_title())

fig = figure('8-tvecs-depth-color')
plot(tvecsDepth)
plot(tvecsColor/1000)
savefig(fig.canvas.get_window_title())

tvecsColorOrig = tvecsColor

'''
---------------测试对比 ta, tb ：

对于 cv, color, extrinsics.xml:
先转到物体旋转：
Ri' := Ri.T
ti' := -Ri.T * ti
t0' = -R0.T * t0

ta = Rab.T * (Rb * tab + tb - tab)
'''
tvecsColor = tvecsColorOrig / 1000
t0c = tvecsColor[0]
t0d = tvecsDepth[0]
deltatColor = np.asarray([np.dot(matColor[i], t0c-tvecsColor[i]) for i in range(tvecsColor.shape[0])])
tbColor = deltatColor
tCV2PCL = np.asarray([(np.dot(-R0.T, matColor[i]).dot(tvecsColor[i]) + t0c + t0d) for i in range(tvecsColor.shape[0])]) #√

'''
对于 pcl_kinfu_app, depth, pose_file.csv
ta = ΔtiDepth = tid - Rid * t0d
'''
deltatDepth = tvecsDepth - np.asarray([np.dot(matDepth[i][:3, :3], t0d) for i in range(tvecsDepth.shape[0])])
taDepth = deltatDepth

fig = figure('9-tCV2PCL-deltatDepth')
plot(tCV2PCL)
plot(deltatDepth)
savefig(fig.canvas.get_window_title())

fig = figure('10-tvecsDepth-tCV2PCL')
plot(tvecsDepth)
plot(tCV2PCL)
savefig(fig.canvas.get_window_title())

'对比 pcl, opencv 的 r, t（转换后），求 RMSEe, RMSEt'
ne = min(eulerColor2.shape[0], eulerDepth.shape[0])
ediff = eulerColor2[:ne] - eulerDepth[:ne]
rmsee = np.sqrt(np.square(ediff).mean(axis=0))

nt = min(tCV2PCL.shape[0], tvecsDepth.shape[0])
tdiff = tCV2PCL[:nt] - tvecsDepth[:nt]
rmset = np.sqrt(np.square(tdiff).mean(axis=0))

print 'rmsee, rmset:'
print '%.3f, %.3f, %.3f'%tuple(rmsee)
print '%.3f, %.3f, %.3f'%tuple(rmset)
# print ', '.join(['%.3f']*rmsee.size)%tuple(rmsee) #good, √


(90L, 4L)
(90L, 3L)
rmsee, rmset:
0.007, 0.010, 0.015
0.011, 0.007, 0.011


In [49]:
def printErrorOnIdx(error, indices):
    ur'打印error列表在 indices 序号上的值'
    print np.array2string(error[indices], precision=3)
    pass

absEdiff = abs(ediff)
print absEdiff.shape

'某 ids 几个序号 R 误差'
# ids = [22, 45, 67]
ids = [515, 1030, 1545]
printErrorOnIdx(absEdiff, ids)

'前10帧 R 误差绝对值'
# printErrorOnIdx(absEdiff, range(10))

'ids T误差'
printErrorOnIdx(abs(tdiff), ids)


(2061L, 3L)
[[ 0.016  0.016  0.035]
 [ 0.     0.005  0.008]
 [ 0.     0.046  0.028]]
[[ 0.018  0.032  0.015]
 [ 0.002  0.014  0.014]
 [ 0.023  0.004  0.022]]


In [17]:
a = rmsee
', '.join(['%.3f']*a.size)%tuple(a)

'0.006, 0.010, 0.015'

In [269]:
e1 = np.array([10,20,30])*np.pi/180
m1 = tf.e2m(*e1, axes='rxyz')
np.asarray(tf.m2e(m1, axes='rxyz'))*180/np.pi

e2 = -e1
m2 = tf.e2m(*e2[::-1], axes='rxyz')
print 'e1:', e1
print 'm1:', m1
print 'e2:', e2
print 'm2:', m2

print 'e2::-1,',e2[::-1]

e1: [ 0.17453293  0.34906585  0.52359878]
m1: [[ 0.81379768 -0.46984631  0.34202014  0.        ]
 [ 0.54383814  0.82317294 -0.16317591  0.        ]
 [-0.20487413  0.31879578  0.92541658  0.        ]
 [ 0.          0.          0.          1.        ]]
e2: [-0.17453293 -0.34906585 -0.52359878]
m2: [[ 0.92541658  0.16317591 -0.34202014  0.        ]
 [ 0.01802831  0.88256412  0.46984631  0.        ]
 [ 0.37852231 -0.44096961  0.81379768  0.        ]
 [ 0.          0.          0.          1.        ]]
e2::-1, [-0.52359878 -0.34906585 -0.17453293]


In [173]:
'测试 xyz -> yzx 坐标轴变换, 是否效果仅仅是交换坐标轴？ 不是！'

figure('xyz')
eulerDepth = np.asarray([tf.q2e([q[1], q[2], q[3], q[0]], axes='rxyz') for q in rvecsDepth])
plot(eulerDepth, )

figure('yzx')
eulerDepth = np.asarray([tf.q2e([q[1], q[2], q[3], q[0]], axes='ryzx') for q in rvecsDepth])
plot(eulerDepth, )


In [5]:
'some tests:'
# 1. from doc:
a = tf.euler_from_quaternion([0.06146124, 0, 0, 0.99810947])
print type(a)
print np.allclose(a, [0.123, 0, 0])

'2. w 应放在最后：'
print tf.euler_from_quaternion([0.382683,0,0,0.92388,])
print tf.euler_from_quaternion([0.382683,0,0,0.92388,], axes='sxyz')

# 0.665976,0.482963,0.29995,0.482963
print tf.euler_from_quaternion([0.482963,0.29995,0.482963,0.665976,], axes='rxyz')

'0 四元数'
print tf.euler_from_quaternion([0, 0, 0, 1], axes='rxyz')
print tf.euler_from_quaternion([0, 0, 0, 1], axes='sxyz')


<type 'tuple'>
True
(0.7853970066908716, -0.0, 0.0)
(0.7853970066908716, -0.0, 0.0)
(0.7853981633974483, 1.0471968266705904, 0.7853981633974484)
(-0.0, 0.0, -0.0)
(0.0, -0.0, 0.0)


In [3]:
'''测试: 'ryzx', 是仅指定 yzx 旋转顺序呢， 还是同时指定 ai, aj, ak 分别代表的轴为 y, z, x 呢？ 后者 √
'''
eu = np.asarray([45,0,0])*np.pi/180
print np.array(tf.m2e(tf.e2m(*eu, axes='ryzx')[:3, :3], axes='rxyz'))*180/np.pi
print 'yzx:', tf.e2m(*eu, axes='ryzx')
print 'xyz:', tf.e2m(*eu, axes='rxyz')

'---------------another:'
eu = np.asarray([10,20,30])*np.pi/180
print '@@@:', tf.e2m(*eu, axes='rxyz')
eu2 = -np.asarray([30,20,10])*np.pi/180
print '@@@:', tf.e2m(*eu2, axes='rzyx').T #inversse
print np.allclose(tf.e2m(*eu, axes='rxyz'), tf.e2m(*eu2, axes='rzyx').T)
# tf.e2m(*eu, axes='rxyz')-tf.e2m(*eu, axes='rzyx').T

[  0.  45.  -0.]
yzx: [[ 0.70710678  0.          0.70710678  0.        ]
 [ 0.          1.         -0.          0.        ]
 [-0.70710678  0.          0.70710678  0.        ]
 [ 0.          0.          0.          1.        ]]
xyz: [[ 1.         -0.          0.          0.        ]
 [ 0.          0.70710678 -0.70710678  0.        ]
 [ 0.          0.70710678  0.70710678  0.        ]
 [ 0.          0.          0.          1.        ]]
@@@: [[ 0.81379768 -0.46984631  0.34202014  0.        ]
 [ 0.54383814  0.82317294 -0.16317591  0.        ]
 [-0.20487413  0.31879578  0.92541658  0.        ]
 [ 0.          0.          0.          1.        ]]
@@@: [[ 0.81379768 -0.46984631  0.34202014  0.        ]
 [ 0.54383814  0.82317294 -0.16317591  0.        ]
 [-0.20487413  0.31879578  0.92541658  0.        ]
 [ 0.          0.          0.          1.        ]]
True


In [27]:
'测试： 欧拉角 -> 四元数， 一一对应， 还是多对一？ 万向锁'
e1 = np.asarray([30, 90, -40])*np.pi/180
e2 = np.asarray([70, 90, 0])*np.pi/180
print np.allclose(tf.e2q(*e1, axes='sxyz'), tf.e2q(*e2, axes='sxyz'))

e1 = np.asarray([30, 90, -40])*np.pi/180
e2 = np.asarray([-10, 90, 0])*np.pi/180
print np.allclose(tf.e2q(*e1, axes='rxyz'), tf.e2q(*e2, axes='rxyz'))
# print tf.e2q(*e2, axes='rxyz')

'e->q->e2， e!=e2， 一个四元数对应多个欧拉角'
e1 = np.asarray([30, 90, -40])*a2r
q1r = tf.e2q(*e1, axes='rxyz')
print np.asarray(tf.q2e(q1r, axes='rxyz'))*r2a

'e1->m->e2, e1!=e2, 一个旋转矩阵对应多个欧拉角'
m1 = tf.e2m(*e1, axes='rxyz')
print np.asarray(tf.m2e(m1, axes='rxyz'))*r2a

'确实， 一个旋转矩阵对应多个欧拉角'
# print tf.e2m(*e1, axes='rxyz')
# print tf.e2m(*e2, axes='rxyz')
# print tf.e2m(*e1, axes='rxyz') == tf.e2m(*e2, axes='rxyz')
print np.allclose(tf.e2m(*e1, axes='rxyz'), tf.e2m(*e2, axes='rxyz'))

"测试 q -> rm -> rm.T -> q' 与 q 关系: cos部不变， sin部取反， 注意 tf库是 xyzw 顺序， w在最后"
e1 = np.asarray([10,20,30])*a2r
q1 = tf.e2q(*e1, axes='rxyz')
m1 = tf.q2m(q1)
m2 = m1.T
q2 = tf.m2q(m2)
print q1, q2


True
True
[ -0.  90. -10.]
[ -0.  90. -10.]
True
[ 0.12767944  0.14487813  0.26853582  0.94371436] [-0.12767944 -0.14487813 -0.26853582  0.94371436]


In [44]:
e1 = np.asarray([10, 20, 30])*a2r
e2 = np.asarray([40, 20, 30])*a2r
q1 = tf.e2q(*e1, axes='rxyz')
q2 = tf.e2q(*e2, axes='rxyz')
print [q1[3]]+q1[:3].tolist() #w 放前面
tf.m2q(tf.q2m(q1))


[0.9437143641474891, 0.12767944069578063, 0.14487812541736916, 0.2685358227515692]


array([ 0.12767944,  0.14487813,  0.26853582,  0.94371436])

In [ ]:
m1 = tf.e2m

In [117]:
'测试： 两不同物体坐标系 a, b 在同一世界坐标系下，Rb -> Ra 怎么做？'

e1 = np.asarray([10,20,30])*np.pi/180
ma = tf.e2m(*e1, axes='rxyz')
# e2 = np.asarray([10,20,30])*np.pi/180
mb = tf.e2m(*e1, axes='ryzx')
print 'ma:\n', ma
print 'mb:\n', mb
mx = tf.e2m(np.pi/2, 0, 0, 'rxyz') #坐标系旋转 -90°， 物体旋转 +90°； tf.xxx 是旋转物体
mz = tf.e2m(0, 0, np.pi/2, 'rxyz')
print 'mx:', mx
print 'mz:', mz
Rab = np.dot(mz, mx)
print 'Rab:', Rab
# Rab = np.array([[0, 0, 1, 0], [1, 0, 0, 0], [0, 1, 0, 0], [0,0,0,1]])
# print 'mx * mz:', Rab
mba = np.dot(Rab.T, mb).dot(Rab)
print 'mba:\n', mba
print 'mba-ma:', np.dot(ma.T, mba)
print np.array(tf.m2e(mb, 'ryzx'))*180/np.pi

ma:
[[ 0.81379768 -0.46984631  0.34202014  0.        ]
 [ 0.54383814  0.82317294 -0.16317591  0.        ]
 [-0.20487413  0.31879578  0.92541658  0.        ]
 [ 0.          0.          0.          1.        ]]
mb:
[[ 0.92541658 -0.20487413  0.31879578  0.        ]
 [ 0.34202014  0.81379768 -0.46984631  0.        ]
 [-0.16317591  0.54383814  0.82317294  0.        ]
 [ 0.          0.          0.          1.        ]]
mx: [[  1.00000000e+00   0.00000000e+00  -0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   6.12323400e-17  -1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.00000000e+00   6.12323400e-17   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
mz: [[  6.12323400e-17  -1.00000000e+00  -0.00000000e+00   0.00000000e+00]
 [  1.00000000e+00   6.12323400e-17   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
Rab:

In [7]:
'测试： cv2.FileStorage'
# cv2.cv.Load(extrinsics_xml) #cv1 只能用来 load iplimage
# 没文档， 不会写
fs = cv2.FileStorage(extrinsics_xml, cv2.FILE_STORAGE_READ)
rt = fs.root()
rt.size()

223L

In [210]:
'''
下面是另一些测试：
1. 测试一个旋转矩阵 list 统一左乘 R0.T 的结果，是否统一偏移了相同角度？
'''
cnt = 100
xang = (np.random.random(cnt) - .5) * np.pi * 2
yang = (np.random.random(cnt) - .5) * np.pi
zang = (np.random.random(cnt) - .5) * np.pi * 2
eus = np.asarray([xang, yang, zang])
# print eus
eus = eus.T
# print eus

In [212]:
'接上个 cell： 测试一个旋转矩阵 list 统一左乘 R0.T 的结果，是否统一偏移了相同角度？'
amode = 'sxyz'
# eus_mat = []
# for eu in eus:
#     eus_mat.append(tf.euler_matrix(*eu, axes=amode))
# eus_mat = np.asarray(eus_mat)
eus_mat = np.asarray([tf.euler_matrix(*eu, axes=amode) for eu in eus])
eus_mat2 = eus_mat.copy()

em0 = eus_mat[0]
for i, emi in enumerate(eus_mat):
#     emi = np.dot(em0.T, emi) #local, wrong ×
    eus_mat2[i] = np.dot(em0.T, emi)
    print '--', eus_mat2[i]
    pass

eus2 = np.asarray([tf.euler_from_matrix(eum, axes=amode) for eum in eus_mat2])

which_axis = 0
figure('eus')
plot(eus[:, which_axis])
figure('eus2')
plot(eus2[:, which_axis])


-- [[  1.00000000e+00   0.00000000e+00  -2.77555756e-17   0.00000000e+00]
 [  0.00000000e+00   1.00000000e+00   5.55111512e-17   0.00000000e+00]
 [ -2.77555756e-17   5.55111512e-17   1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
-- [[-0.69513184  0.22299768 -0.68342063  0.        ]
 [ 0.14738731 -0.88626706 -0.4390987   0.        ]
 [-0.70361119 -0.40595902  0.58320542  0.        ]
 [ 0.          0.          0.          1.        ]]
-- [[ 0.75757559  0.60877803  0.23551758  0.        ]
 [-0.63999784  0.76370847  0.08457033  0.        ]
 [-0.12838221 -0.21479916  0.96818352  0.        ]
 [ 0.          0.          0.          1.        ]]
-- [[ 0.62390541  0.42772093 -0.65406181  0.        ]
 [ 0.75924309 -0.13342766  0.63698272  0.        ]
 [ 0.18518091 -0.89400888 -0.40799039  0.        ]
 [ 0.          0.          0.          1.        ]]
-- [[-0.90530255  0.36717758 -0.21356011  0.        ]
 [ 0.39919708  0.56364658 -0.72314

In [225]:
'(20,20,20).T * (60,60,60) 不等于 (40,40,40), 无论 sxyz, rxyz'
'欧拉角是不可传递的'

# e1 = np.asarray([np.pi/9]*3)
# e2 = np.asarray([np.pi/3]*3)
e1 = np.asarray([np.pi/9, np.pi/9, 0])
e21 = np.asarray([np.pi/3, np.pi/3, 0])
e22 = np.asarray([np.pi/3, np.pi/2, 0])

m1 = tf.e2m(*e1)
m21 = tf.e2m(*e21)
m31 = np.dot(m1.T, m21)
print np.array(tf.euler_from_matrix(m31))*180/np.pi
m22 = tf.euler_matrix(*e22)
m32 = np.dot(m1.T, m22)
print np.array(tf.euler_from_matrix(m32))*180/np.pi

m1 = tf.euler_matrix(*e1, axes='rxyz')
m21 = tf.euler_matrix(*e21, axes='rxyz')
m31 = np.dot(m1.T, m21)
print np.array(tf.euler_from_matrix(m31, axes='rxyz'))*180/np.pi
m22 = tf.euler_matrix(*e22, axes='rxyz')
m32 = np.dot(m1.T, m22)
print np.array(tf.euler_from_matrix(m32, axes='rxyz'))*180/np.pi


[ 34.58623312  37.15855414 -16.01289549]
[ 13.21917889  62.00910928 -43.21917889]
[ 26.09741558  43.06254932  17.51217232]
[  6.59354995e-15   7.00000000e+01   4.00000000e+01]


In [217]:
'global/local; static/rotating frame 的关系； from 杜宇笔记'
print tf.euler_matrix(10, 20, 30, axes='rxyz')
print tf.euler_matrix(30, 20, 10, axes='szyx')
print np.all(tf.euler_matrix(10, 20, 30, axes='rxyz')==tf.euler_matrix(30, 20, 10, axes='szyx'))


[[ 0.06294725  0.40319798  0.91294525  0.        ]
 [ 0.75241845 -0.62014526  0.22200526  0.        ]
 [ 0.65567074  0.67294223 -0.34241004  0.        ]
 [ 0.          0.          0.          1.        ]]
[[ 0.06294725  0.40319798  0.91294525  0.        ]
 [ 0.75241845 -0.62014526  0.22200526  0.        ]
 [ 0.65567074  0.67294223 -0.34241004  0.        ]
 [ 0.          0.          0.          1.        ]]
True
